FROM python:3.12


LABEL maintainer="hamzawaheed057@gmail.com"

RUN apt-get update && apt-get install -y \
build-essential \
libpq-dev \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /code/

RUN pip install poetry

COPY . /code/

RUN poetry install

EXPOSE 8000

CMD ["uvicorn", "run", "class1_helloworld.main:app", "--host", "0.0.0.0","--reload"]